FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /App
COPY . ./

COPY api.csproj /App/
RUN dotnet restore api.csproj

COPY . .
RUN dotnet publish -c Release -o out

FROM  mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /App
COPY --from=build /App/out ./
ENTRYPOINT ["dotnet", "api.dll"]